cmake_minimum_required(VERSION 3.5)
set(CMAKE_CXX_STANDARD 23)
set(CXX_STANDARD_REQUIRED ON)
project(Verifier)

include(lib/z3/CMakeLists.txt)
include_directories(lib/cudd/cudd)
include_directories(lib/cudd/cplusplus)
include_directories(lib/cudd/dddmp)
include_directories(lib/cudd/epd)
include_directories(lib/cudd/mtr)
include_directories(lib/cudd/obj)
include_directories(lib/cudd/st)
include_directories(lib/cudd/util)
include_directories(lib/cudd/obj)
include_directories(lib/parse)
include_directories(lib/parserlib)
add_subdirectory(lib/cudd)
add_subdirectory(src)

add_executable(Verifier Verifier.cpp)
target_link_libraries(Verifier libz3 parser)
