# Dockerfile-Base
FROM ubuntu:latest

# System-Pakete installieren (nur das Nötigste)
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        build-essential \
        cmake \
        ninja-build \
        git \
        python3 \
        python3-venv \
        python3-pip \
        openjdk-17-jre-headless \
        libz3-dev \
    && rm -rf /var/lib/apt/lists/*

# ANTLR Jar aus deinem Projekt einbinden
COPY lib/antlr/antlr-4.13.1-complete.jar /usr/local/lib/antlr-4.13.1-complete.jar
ENV ANTLR_EXECUTABLE=/usr/local/lib/antlr-4.13.1-complete.jar

WORKDIR /verifier
CMD ["bash"]
